const axios = require('axios');
const {
    before,
    after,
    it,
    describe
} = require('mocha');
const {serverUrl} = require('../mock.config');
const assert = require('assert');


describe('QueryRule Integration Test', function () {

    before(async function () {
        const authorizationRule = {
            applicationId: 'daas',
            masterKey: 'daas',
            Authorization: {
                rules: {
                    'create.*': `return true;`,
                    'query.*': `return true;`,
                }
            },
            CreateTest: [
                {
                    id: 'joshua',
                    name: 'joshua',
                    likes: {
                        movies: 'Action'
                    }
                },
                {
                    name: 'mshana',
                    height: '130cm',
                    likes: {
                        movies: 'Action'
                    }
                },
                {
                    name: 'eitan',
                    age: 20,
                    address: {
                        city: 'Dar Es Salaam'
                    }
                }
            ],
        }
        await axios.post(serverUrl, authorizationRule);
    });

    after(async function () {
    });

    it('should query by id when applicationId supplied and authorization is anonymously', async function () {
        const queryRule = {
            applicationId: 'daas',
            QueryTest: {
                id: 'joshua',
                return: []
            }
        };
        const response = await axios.post(serverUrl, queryRule);
        // console.log(response.data);
        assert(response.data.errors === undefined);
        assert(response.data['ResultOfQueryTest'] !== undefined);
        assert(typeof response.data['ResultOfQueryTest'] === "object");
        assert(!Array.isArray(response.data['ResultOfQueryTest']));
        assert(response.data['ResultOfQueryTest'].id === "joshua");
    });

    it('should query with empty fields when applicationId supplied and authorization is anonymously', async function () {
        const queryRule = {
            applicationId: 'daas',
            QueryTest: {}
        };
        const response = await axios.post(serverUrl, queryRule);
        // console.log(response.data);
        assert(response.data.errors === undefined);
        assert(response.data['ResultOfQueryTest'] !== undefined);
        assert(typeof response.data['ResultOfQueryTest'] === "object");
        assert(Array.isArray(response.data['ResultOfQueryTest']));
        assert(response.data['ResultOfQueryTest'][0].id !== undefined);
        assert(typeof response.data['ResultOfQueryTest'][0].id === "string");
    });

    it('should  not query if applicationId not supplied and authorization is anonymously', async function () {
        const queryRule = {
            QueryTest: {
                id: 'joshua',
                return: []
            }
        };
        try {
            await axios.post(serverUrl, queryRule);
        } catch (e) {
            assert(e.response.status === 401);
            assert(e.response.data.message === 'unauthorized');
            assert(typeof e.response.data === 'object');
        }
    });

    it('should query by filter when applicationId supplied and authorization is anonymously', async function () {
        const queryRule = {
            applicationId: 'daas',
            QueryTest: {
                filter: {
                    name: 'eitan'
                },
                return: []
            }
        };
        const response = await axios.post(serverUrl, queryRule);
        // console.log(response.data);
        assert(response.data.errors === undefined);
        assert(response.data['ResultOfQueryTest'] !== undefined);
        assert(Array.isArray(response.data['ResultOfQueryTest']));
        assert(response.data['ResultOfQueryTest'][0].name === "eitan");
        assert(response.data['ResultOfQueryTest'].length === 1);
    });

    it('should query by autogenerated Id from mongodb when applicationId supplied and authorization is anonymously', async function () {
        let objectId;
        const createRule = {
            applicationId: 'daas',
            CreateTest: {
                name: 'olive',
                age: 30
            }
        }
        const createResponse = await axios.post(serverUrl, createRule);
        objectId = createResponse.data['ResultOfCreateTest'].id;

        const queryRule = {
            applicationId: 'daas',
            QueryTest: {
                id: objectId,
                return: []
            }
        };
        const response = await axios.post(serverUrl, queryRule);
        // console.log(response.data);
        assert(response.data.errors === undefined);
        assert(response.data['ResultOfQueryTest'] !== undefined);
        assert(!Array.isArray(response.data['ResultOfQueryTest']));
        assert(response.data['ResultOfQueryTest'].name === "olive");
        assert(response.data['ResultOfQueryTest'].age === 30);
        assert(response.data['ResultOfQueryTest'].id === objectId);
    });

});
