export enum FactoryIdentifier {
    GetDataFn,
    // UpsertDataFn,
    // UpsertNodeFn,
    // GetNodeFn,
    // GetNodesFn,
    // PurgeNodeFn,
    InitDatabaseFn,
    GetManyDataFn,
    CreateManyData,
    PurgeDataFn,
    PurgeManyDataFn,
    UpdateManyDataFn,
    UpdateDataFn,
    CreateDataFn,
    AggregateDataFn,
}
